[33m772b3a5[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mstable[m[33m, [m[1;31morigin/stable[m[33m)[m handle error calculation form complete business profile
[33mb866819[m change model gemini karna limit for presentasi
[33maa6affe[m added vercel json
[33m3573abb[m remove console logs
[33m258405e[m coba semoga jalan
[33m8b7a1e6[m changed base_url
[33m1e0c1bc[m added toml
[33m4a0fa28[m fixed errors for build
[33m3fb52d3[m hide KUR status in financial overview
[33m4343b86[m number format on business proposal fix
[33mc898aff[m make prettier notif success save in quiz_profile
[33ma0b5396[m add alert when delete draft proposal
[33mc963f48[m add new dashboard
[33mef2caf1[m add redirect function to button in business card
[33m6de7dc0[m add function delete asset button in financial overview
[33md082392[m make dynamic payment methods in financial overview
[33m6ca47cf[m make more dynamic payment methods in business profile overview
[33m3018a52[m add paymentMethod field to business profile form, models, and dashboard summary
[33m8c442c7[m fix format table header n kur text wrapping
[33m1dbee7e[m revised ui problems, added assets calculation, added kur eligibility validation
[33m3f42997[m added validation and ui to amort form
[33med4580d[m added: table sorting features
[33m7fc1616[m finalized: chart page for each amort
[33m0dbc9b0[m Merge branch 'main' of https://github.com/Briant-s/project_se_-3
[33m9b30fb8[m eligibility quiz alternative card
[33m7ae6258[m added chart for each amort calc, added utils for calculating amort data
[33m3dd37ab[m add asset form in quiz profile
[33m59b0f9e[m revised main.py again
[33m98d7987[m reverted back main.py
[33m13a3f31[m added: not final LoanSummary metrics to amort calc page
[33me365c48[m added: now kur counts the health status aswell
[33mbe602bf[m added: utility for calculating health status and total installment
[33m3d95905[m save bntr
[33m89a4edd[m revised some changes
[33m75d89c6[m revised: profilequiz form businessAge, monthlyAvgIncome, monthlyProfitLoss
[33mc4ccdc3[m refactor: businessProfile quiz typing
[33me05d7ff[m redirect first time sign up to quiz profile page
[33mdd34a9b[m add format paragraf and numbering order to PDF AI Business Proposal
[33m52c4bac[m added: EligOverview(fix ui to table format, new calc button func), LoanCalc(get kur by type)
[33mb14acef[m added: Count KUR by type
[33m7cdb685[m added colors, removed gradient.ts
[33me72befc[m benerin container gemes business proposal
[33m3451670[m validation form complete, redirect button ke page, synchronize progress sidebar
[33m8f0e32d[m dsuru gio nambahin loader pas fetching
[33m001f985[m feli bau
[33m2a4dd7b[m delete ai proposal when business propsal get update
[33m1b45362[m connect Gemini API and integrated pdf business proposal with AI generated, but still can change if won't generated by ai (not yet to route automaticly)
[33m1391863[m revised ui for loan simulations page, api MIGHT be buggy note if so
[33m6c7e528[m Merge branch 'main' of https://github.com/Briant-s/project_se_-3
[33m79f7408[m add API to Supbase at business proposal, can read, insert, update and delete input for business proposal
[33maba5eb5[m added soon-to-be ui for loan sim calc page
[33m2f71f86[m removed document prep from routing
[33m59aa8c8[m revise credit overview ui, added join to amort list api
[33md2a6257[m added api for amort list with datetime cutoff, ui revisions for credit overview
[33m6334567[m proposal list + pdf viewer untuk proposal + dummy import pada app layout + dummy untuk proposal
[33mdfdea86[m formulir business proposal
[33m9097d16[m delete credit purpose
[33mb7921a4[m update credit class match supa credit purpose, tenor n limit credit
[33ma484755[m created template fro credit overview
[33m69152ac[m adjusted amort form to take kur type and principle amount
[33m708ccde[m added new business email & contact form to profile quiz
[33m09b5295[m quiz progress table
[33m06fed51[m nambah assets utk jaminan
[33mc353c89[m now business & financial overview connects to profile quiz
[33m043e5af[m bikin class
[33m49aa847[m Merge branch 'main' of https://github.com/Briant-s/project_se_-3 merge business profile progress into main
[33mbd739f2[m add api Create, Read, Update at businessProfile
[33m4ab4cf8[m added user profile, removed some unused links
[33m3a0fa06[m add businessProfile models
[33m456ca2c[m deletion pop up
[33ma31e0b8[m update ui
[33mcee9465[m updated requirements.txt
[33m367fc09[m remove unused page
[33me8b63ea[m added each page amort item
[33mc28ced9[m fixed update & delete
[33md7f7758[m now amort list is per user, removed some console logs
[33me64d705[m add login and register with google
[33m6dd8b34[m handle auth error message when submit in register page
[33m70c5059[m handle auth error message when submit in login page
[33ma5ba43c[m add validation input for login page, but not handle auth error message when submit & not handle remember me
[33m3a6b804[m add validation input for registration page, but not handle auth error message when submit
[33m9c1d321[m change env variables
[33mffa078f[m can now do crud operations in loan calculator page, might have bugs, no loading yet, & not yet user specific
[33mb707fb6[m progress on backend setup, change url path for credit routes
[33m8ea94aa[m now must be logged in to access dashboard
[33mc128855[m renew some stuff
[33m1882612[m ensuring .env is in .gitignore
[33mb5b7c8d[m removed .env and added to gitignore
[33mde75385[m remove .env and added to .gitignore
[33m0add201[m connected to supabase, can now login/register/signout, added new dependencies
[33m88c42a6[m added login & regis page, links to one another
[33m8ca803e[m refactor app.tsx, seperate it into applayout and app routing
[33m2696376[m login
[33m0389159[m update ui financial overview
[33m4e99743[m add form validation on profile quiz
[33m3006df0[m add page profile quiz
[33m52a26a9[m update ui business overview
[33m73e6d7e[m add space between on taskbar
[33m38fdf9b[m update navbar
[33ma715adc[m added back button
[33m6025d54[m changed text size
[33mb657c8b[m added temp layout for financial overview
[33m99c661e[m business profile revision
[33ma25a26c[m ui changes to business profile
[33m7e3d615[m button in elig now reroutes to other pages
[33m9ff4047[m added cards to overview
[33mc70b583[m added charts to elig_overview
[33m0d9fba5[m ui for business profile
[33m244781f[m added more pages in nav, haven't created the files though
[33m95974c6[m wip
[33mbec3d7c[m testing github notifs
[33m62be577[m added nav link routing
[33ma82b0ae[m added navbar template for now, added a icon and ui dependencies
[33m95d1c4a[m fixing multi device syncing
[33me410d75[m added requirements.txt to backend
[33m18e10be[m first_commit
