// import {
//   Document,
//   Page,
//   Text,
//   View,
//   StyleSheet,
// } from "@react-pdf/renderer";

// const styles = StyleSheet.create({
//   page: {
//     padding: 40,
//     fontSize: 11,
//     fontFamily: "Helvetica",
//     color: "#1a1a1a",
//   },
//   coverTitle: {
//     fontSize: 24,
//     fontFamily: "Helvetica-Bold",
//     marginBottom: 8,
//   },
//   coverSubtitle: {
//     fontSize: 13,
//     color: "#555",
//     marginBottom: 4,
//   },
//   coverDate: {
//     fontSize: 10,
//     color: "#888",
//     marginTop: 8,
//   },
//   divider: {
//     borderBottomWidth: 1,
//     borderBottomColor: "#e0e0e0",
//     marginVertical: 12,
//   },
//   sectionHeader: {
//     fontSize: 13,
//     fontFamily: "Helvetica-Bold",
//     marginBottom: 6,
//     marginTop: 4,
//     color: "#1971c2",
//   },
//   label: {
//     fontSize: 10,
//     fontFamily: "Helvetica-Bold",
//     marginBottom: 2,
//     color: "#444",
//   },
//   value: {
//     fontSize: 10,
//     marginBottom: 8,
//     lineHeight: 1.5,
//     color: "#1a1a1a",
//   },
//   row: {
//     flexDirection: "row",
//     gap: 16,
//     marginBottom: 4,
//   },
//   col: {
//     flex: 1,
//   },
//   card: {
//     borderWidth: 1,
//     borderColor: "#e0e0e0",
//     borderRadius: 4,
//     padding: 10,
//     marginBottom: 8,
//   },
//   cardTitle: {
//     fontSize: 10,
//     fontFamily: "Helvetica-Bold",
//     marginBottom: 4,
//     color: "#333",
//   },
// });

// interface MenuItem {
//   name: string;
//   description: string;
//   price: string;
// }

// interface Competitor {
//   name: string;
//   strength: string;
//   weakness: string;
// }

// interface ProposalData {
//   businessName: string;
//   businessDescription: string;
//   visi: string;
//   misi: string;
//   targetPasar: string;
//   psikografi: string;
//   trenPasar: string;
//   competitors: Competitor[];
//   strategiPemasaran: string;
//   pelayananPelanggan: string;
//   menuProduk: MenuItem[];
//   jamOperasional: string;
//   jumlahStaff: string;
//   supplier: string;
//   prosesOperasional: string;
//   modalAwal: string;
//   targetPendapatan: string;
//   analisa: string;
//   kesimpulan: string;
// }

// function Field({ label, value }: { label: string; value: string }) {
//   return (
//     <View>
//       <Text style={styles.label}>{label}</Text>
//       <Text style={styles.value}>{value || "-"}</Text>
//     </View>
//   );
// }

// function AIBusinessProposalPDF({ data }: { data: ProposalData }) {
//   return (
//     <Document>
//       <Page size="A4" style={styles.page}>
//         <View style={{ marginTop: 60, marginBottom: 40 }}>
//           <Text style={styles.coverTitle}>{data.businessName || "AI Business Proposal"}</Text>
//           <Text style={styles.coverSubtitle}>Generated by Gemini AI</Text>
//           <Text style={styles.coverSubtitle}>AI Business Proposal Document</Text>
//           <Text style={styles.coverDate}>
//             Dibuat pada: {new Date().toLocaleDateString("id-ID", { day: "numeric", month: "long", year: "numeric" })}
//           </Text>
//         </View>
//         <View style={styles.divider} />
//         <Field label="Deskripsi Bisnis" value={data.businessDescription} />
//         <View style={styles.row}>
//           <View style={styles.col}>
//             <Field label="Visi" value={data.visi} />
//           </View>
//           <View style={styles.col}>
//             <Field label="Misi" value={data.misi} />
//           </View>
//         </View>
//       </Page>

//       <Page size="A4" style={styles.page}>
//         <Text style={styles.sectionHeader}>Analisis Pasar</Text>
//         <View style={styles.divider} />
//         <Field label="Target Pasar" value={data.targetPasar} />
//         <Field label="Psikografi" value={data.psikografi} />
//         <Field label="Tren Pasar" value={data.trenPasar} />

//         <Text style={[styles.label, { marginTop: 8 }]}>Kompetitor</Text>
//         {data.competitors.map((comp, i) => (
//           <View key={i} style={styles.card}>
//             <Text style={styles.cardTitle}>{comp.name || `Kompetitor ${i + 1}`}</Text>
//             <View style={styles.row}>
//               <View style={styles.col}>
//                 <Text style={styles.label}>Kelebihan</Text>
//                 <Text style={styles.value}>{comp.strength || "-"}</Text>
//               </View>
//               <View style={styles.col}>
//                 <Text style={styles.label}>Kelemahan</Text>
//                 <Text style={styles.value}>{comp.weakness || "-"}</Text>
//               </View>
//             </View>
//           </View>
//         ))}
//       </Page>

//       <Page size="A4" style={styles.page}>
//         <Text style={styles.sectionHeader}>Strategi & Produk</Text>
//         <View style={styles.divider} />
//         <Field label="Strategi Pemasaran" value={data.strategiPemasaran} />
//         <Field label="Pelayanan Pelanggan" value={data.pelayananPelanggan} />

//         <Text style={[styles.label, { marginTop: 8 }]}>Menu / Produk</Text>
//         {data.menuProduk.map((item, i) => (
//           <View key={i} style={styles.card}>
//             <View style={styles.row}>
//               <View style={styles.col}>
//                 <Text style={styles.cardTitle}>{item.name || `Produk ${i + 1}`}</Text>
//                 <Text style={styles.value}>{item.description || "-"}</Text>
//               </View>
//               <View>
//                 <Text style={styles.label}>Harga</Text>
//                 <Text style={styles.value}>Rp {item.price || "-"}</Text>
//               </View>
//             </View>
//           </View>
//         ))}
//       </Page>

//       <Page size="A4" style={styles.page}>
//         <Text style={styles.sectionHeader}>Rencana Operasional</Text>
//         <View style={styles.divider} />
//         <View style={styles.row}>
//           <View style={styles.col}>
//             <Field label="Jam Operasional" value={data.jamOperasional} />
//           </View>
//           <View style={styles.col}>
//             <Field label="Jumlah Staff" value={data.jumlahStaff} />
//           </View>
//         </View>
//         <Field label="Supplier" value={data.supplier} />
//         <Field label="Proses Operasional" value={data.prosesOperasional} />

//         <Text style={[styles.sectionHeader, { marginTop: 12 }]}>Rencana Keuangan</Text>
//         <View style={styles.divider} />
//         <View style={styles.row}>
//           <View style={styles.col}>
//             <Field label="Modal Awal" value={`Rp ${Number(data.modalAwal || 0).toLocaleString("id-ID")}`} />
//           </View>
//           <View style={styles.col}>
//             <Field label="Target Pendapatan / Bulan" value={`Rp ${Number(data.targetPendapatan || 0).toLocaleString("id-ID")}`} />
//           </View>
//         </View>
//         <Field label="Analisa Keuangan" value={data.analisa} />

//         <Text style={[styles.sectionHeader, { marginTop: 12 }]}>Kesimpulan</Text>
//         <View style={styles.divider} />
//         <Text style={styles.value}>{data.kesimpulan || "-"}</Text>
//       </Page>
//     </Document>
//   );
// }

// export default AIBusinessProposalPDF;
// export type { ProposalData };

import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: "Helvetica",
    color: "#1a1a1a",
  },
  coverTitle: {
    fontSize: 24,
    fontFamily: "Helvetica-Bold",
    marginBottom: 8,
  },
  coverSubtitle: {
    fontSize: 13,
    color: "#555",
    marginBottom: 4,
  },
  coverDate: {
    fontSize: 10,
    color: "#888",
    marginTop: 8,
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
    marginVertical: 12,
  },
  sectionHeader: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    marginBottom: 6,
    marginTop: 4,
    color: "#1971c2",
  },
  label: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    marginBottom: 4,
    color: "#444",
  },
  value: {
    fontSize: 10,
    marginBottom: 6,
    lineHeight: 1.5,
    color: "#1a1a1a",
  },
  row: {
    flexDirection: "row",
    gap: 16,
    marginBottom: 4,
  },
  col: {
    flex: 1,
  },
  card: {
    borderWidth: 1,
    borderColor: "#e0e0e0",
    borderRadius: 4,
    padding: 10,
    marginBottom: 8,
  },
  cardTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    marginBottom: 4,
    color: "#333",
  },
});

interface MenuItem {
  name: string;
  description: string;
  price: string;
}

interface Competitor {
  name: string;
  strength: string;
  weakness: string;
}

interface ProposalData {
  businessName: string;
  businessDescription: string;
  visi: string;
  misi: string;
  targetPasar: string;
  psikografi: string;
  trenPasar: string;
  competitors: Competitor[];
  strategiPemasaran: string;
  pelayananPelanggan: string;
  menuProduk: MenuItem[];
  jamOperasional: string;
  jumlahStaff: string;
  supplier: string;
  prosesOperasional: string;
  modalAwal: string;
  targetPendapatan: string;
  analisa: string;
  kesimpulan: string;
}

/**
 * Fungsi vital untuk membersihkan teks bocor \n, \\n, atau /n dari API/Database
 * dan mengubahnya menjadi susunan baris baru yang mengalir ke bawah.
 */
function renderCleanText(rawText: string) {
  if (!rawText) return <Text style={styles.value}>-</Text>;

  // 1. Paksa konversi ke string untuk menghindari error tipe data
  let textString = String(rawText);

  // 2. Tangkap teks literal "\\n", "\n", atau "/n" yang bocor, lalu ubah jadi token standar [SPLIT]
  textString = textString.replace(/\\n/g, "[SPLIT]");
  textString = textString.replace(/\n/g, "[SPLIT]");
  textString = textString.replace(/\/n/g, "[SPLIT]");

  // 3. Pecah berdasarkan token, buang baris kosong yang berlebih
  const lines = textString
    .split("[SPLIT]")
    .map((l) => l.trim())
    .filter((l) => l !== "");

  if (lines.length === 0) return <Text style={styles.value}>-</Text>;

  // 4. Render setiap baris teks ke dalam komponen Text tersendiri agar turun ke bawah
  return lines.map((line, index) => {
    // Opsional: Membersihkan sisa format bold markdown (**) agar teks bersih total
    const cleanLine = line.replace(/\*\*/g, "");

    return (
      <Text key={index} style={styles.value}>
        {cleanLine}
      </Text>
    );
  });
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <View style={{ marginBottom: 8 }}>
      <Text style={styles.label}>{label}</Text>
      {renderCleanText(value)}
    </View>
  );
}

function AIBusinessProposalPDF({ data }: { data: ProposalData }) {
  return (
    <Document>
      {/* HALAMAN 1 */}
      <Page size="A4" style={styles.page}>
        <View style={{ marginTop: 60, marginBottom: 40 }}>
          <Text style={styles.coverTitle}>
            {data.businessName || "AI Business Proposal"}
          </Text>
          <Text style={styles.coverSubtitle}>Generated by Gemini AI</Text>
          <Text style={styles.coverSubtitle}>
            AI Business Proposal Document
          </Text>
          <Text style={styles.coverDate}>
            Dibuat pada:{" "}
            {new Date().toLocaleDateString("id-ID", {
              day: "numeric",
              month: "long",
              year: "numeric",
            })}
          </Text>
        </View>
        <View style={styles.divider} />
        <Field label="Deskripsi Bisnis" value={data.businessDescription} />
        <View style={styles.row}>
          <View style={styles.col}>
            <Field label="Visi" value={data.visi} />
          </View>
          <View style={styles.col}>
            <Field label="Misi" value={data.misi} />
          </View>
        </View>
      </Page>

      {/* HALAMAN 2 */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionHeader}>Analisis Pasar</Text>
        <View style={styles.divider} />
        <Field label="Target Pasar" value={data.targetPasar} />
        <Field label="Psikografi" value={data.psikografi} />
        <Field label="Tren Pasar" value={data.trenPasar} />

        <Text style={[styles.label, { marginTop: 8 }]}>Kompetitor</Text>
        {data.competitors &&
          data.competitors.map((comp, i) => (
            <View key={i} style={styles.card}>
              <Text style={styles.cardTitle}>
                {comp.name || `Kompetitor ${i + 1}`}
              </Text>
              <View style={styles.row}>
                <View style={styles.col}>
                  <Text style={styles.label}>Kelebihan</Text>
                  {renderCleanText(comp.strength)}
                </View>
                <View style={styles.col}>
                  <Text style={styles.label}>Kelemahan</Text>
                  {renderCleanText(comp.weakness)}
                </View>
              </View>
            </View>
          ))}
      </Page>

      {/* HALAMAN 3 */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionHeader}>Strategi & Produk</Text>
        <View style={styles.divider} />
        <Field label="Strategi Pemasaran" value={data.strategiPemasaran} />
        <Field label="Pelayanan Pelanggan" value={data.pelayananPelanggan} />

        <Text style={[styles.label, { marginTop: 8 }]}>Menu / Produk</Text>
        {data.menuProduk &&
          data.menuProduk.map((item, i) => (
            <View key={i} style={styles.card}>
              <View style={styles.row}>
                <View style={styles.col}>
                  <Text style={styles.cardTitle}>
                    {item.name || `Produk ${i + 1}`}
                  </Text>
                  {renderCleanText(item.description)}
                </View>
                <View>
                  <Text style={styles.label}>Harga</Text>
                  <Text style={styles.value}>Rp {item.price || "-"}</Text>
                </View>
              </View>
            </View>
          ))}
      </Page>

      {/* HALAMAN 4 */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionHeader}>Rencana Operasional</Text>
        <View style={styles.divider} />
        <View style={styles.row}>
          <View style={styles.col}>
            <Field label="Jam Operasional" value={data.jamOperasional} />
          </View>
          <View style={styles.col}>
            <Field label="Jumlah Staff" value={data.jumlahStaff} />
          </View>
        </View>
        <Field label="Supplier" value={data.supplier} />
        <Field label="Proses Operasional" value={data.prosesOperasional} />

        <Text style={[styles.sectionHeader, { marginTop: 12 }]}>
          Rencana Keuangan
        </Text>
        <View style={styles.divider} />
        <View style={styles.row}>
          <View style={styles.col}>
            <Field
              label="Modal Awal"
              value={`Rp ${Number(data.modalAwal || 0).toLocaleString("id-ID")}`}
            />
          </View>
          <View style={styles.col}>
            <Field
              label="Target Pendapatan / Bulan"
              value={`Rp ${Number(data.targetPendapatan || 0).toLocaleString("id-ID")}`}
            />
          </View>
        </View>
        <Field label="Analisa Keuangan" value={data.analisa} />

        <Text style={[styles.sectionHeader, { marginTop: 12 }]}>
          Kesimpulan
        </Text>
        <View style={styles.divider} />
        {renderCleanText(data.kesimpulan)}
      </Page>
    </Document>
  );
}

export default AIBusinessProposalPDF;
export type { ProposalData };
